### ISSUE TITLE
need eventbrite link

### ISSUE THREAD

**Issue by drammock** [umn-dash/2023-09-21-umn#1]
@chennesy are you normally the one to set up the eventbrite link for UMN-DASH workshops?  If not LMK and I can try to figure out how it's done.  If so could you add that here (feel free to push directly to `gh-pages` if you don't want to bother with a PR).

**Comment by chennesy** [comment]
Thanks @drammock! We're using a different registration tool this time around, so no need to add the Eventbrite link (or any registration link here since we'll do outreach via UMN channels). So this looks great, thanks for setting it up!
